name: Decrypt git-crypt secrets

inputs:
  key:
    description: git-crypt exported key in base64
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: Install git-crypt
      id: install-git-crypt
      # Make the Nix gods mad.
      run: sudo apt install git-crypt
      shell: bash

    - name: Decrypt git-crypt secrets
      id: git-crypt
      run: git-crypt unlock <(base64 -d <<< "$GIT_CRYPT_KEY")
      env:
        GIT_CRYPT_KEY: ${{ inputs.key }}
      shell: bash
